config/routes.rb
Rails.application.routes.draw do

  root to: 'static_pages#home'
  get    'signup', to: 'users#new'
  get    'login' , to: 'sessions#new'
  post   'login' , to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users do
    member do
      get "followings"
      get "followers"
      get "new_diary"
    end
  end
  resources :words
  resources :diaries
  resources :relationships, only: [:create, :destroy]

end

app/models/diary.rb
class Diary < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 3000 }
  validates :title, presence: true, length: { maximum: 100 }
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ActiveRecord::Base
    before_save { self.email = self.email.downcase }
    validates :name, presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
    validates :location,length:{maximum:30}
    validates :hobby,length:{maximum:30}
    validates :thema,length:{maximum:30}
    has_many :diaries ,class_name:"Diary"
    
    has_many :words
    
    has_many :following_relationships, class_name:  "Relationship",
                                     foreign_key: "follower_id",
                                     dependent:   :destroy
    has_many :following_users, through: :following_relationships, source: :followed
    
    has_many :follower_relationships, class_name:  "Relationship",
                                    foreign_key: "followed_id",
                                    dependent:   :destroy
    has_many :follower_users, through: :follower_relationships, source: :follower

    has_secure_password
    
    # 他のユーザーをフォローする
    def follow(other_user)
        following_relationships.find_or_create_by(followed_id: other_user.id)
    end
    
    # フォローしているユーザーをアンフォローする
    def unfollow(other_user)
        following_relationship = following_relationships.find_by(followed_id: other_user.id)
        following_relationship.destroy if following_relationship
    end
    
    # あるユーザーをフォローしているかどうか？
    def following?(other_user)
        following_users.include?(other_user)
    end
    
    def feed_items
      Diary.where(user_id: following_user_ids + [self.id])
    end
end

app/models/word.rb
class Word < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true
  validates :keyword, presence: true, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  private
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end
end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
  before_action :logged_in_user, only: [:create]
  
  def show
    @diary = Diary.find(params[:id])
  end
  
  def create
    @diary = current_user.diaries.build(diary_params)
    if @diary.save
      flash[:success] = "日記が投稿されました！"
      redirect_to root_url
    else
      @feed_items = current_user.feed_items.includes(:user).order(created_at: :desc)
      render 'static_pages/home'
    end
  end
  
  def destroy
    @diary = current_user.diaries.find_by(id: params[:id])
    return redirect_to root_url if @diary.nil?
    @diary.destroy
    flash[:success] = "日記が削除されました"
    redirect_to request.referrer || root_url
  end
  
  private
  def diary_params
    params.require(:diary).permit(:content,:title)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
    before_action :logged_in_user

      def create
        @user = User.find(params[:followed_id])
        current_user.follow(@user)
      end
    
      def destroy
        @user = current_user.following_relationships.find(params[:id]).followed
        current_user.unfollow(@user)
      end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      flash[:info] = "logged in as #{@user.name}"
      redirect_to @user
    else
      flash[:danger] = 'invalid email/password combination'
      render 'new'
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @diary = current_user.diaries.build
      @feed_items = current_user.feed_items.includes(:user).order(created_at: :desc)
    end  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def show
   @user = User.find(params[:id])
   @diaries = @user.diaries.order(created_at: :desc)
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
    if (current_user != @user)
      redirect_to root_path
    end
  end
  
  def update
    @user = User.find(params[:id])
     # @userは編集対象ユーザー
    if (current_user != @user)
      redirect_to root_path
      return
    end
    
    if (@user.update(user_profile))
      redirect_to @user
    else
      flash.now[:danger] = "更新できませんでした"
      render :edit
    end
  end
  
  def followings
    @user = User.find(params[:id])
    @f_users = @user.following_users
  end
  
  def followers
    @user = User.find(params[:id])
    @f_users = @user.follower_users
  end
  
  def user_diaries
    @user = User.find(params[:id])
    @user_diaries = @user.diaries
  end
  
  def new_diary
    
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end
  
  def user_profile
    params.require(:user).permit(:name,:email,:password,:password_confirmation,:location,:hobby,:thema)
  end  
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
    before_action :logged_in_user
      def create
        @word = current_user.words.build(word_params)
            if @word.save
              redirect_to :back
              #link_to URI.escape("http://ejje.weblio.jp/content/#{@word.keyword}"), 
              #:onclick=>"window.open(this.href, 'height=400, width=800');return false;"
              #redirect_to URI.escape("http://ejje.weblio.jp/content/#{@word.keyword}"), target:"_blank"
            else
              @feed_items = current_user.feed_items.includes(:user).order(created_at: :desc)
              render 'static_pages/home'
            end
      end
      
      private
      def word_params
        params.require(:word).permit(:keyword)
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end

  def store_location
    session[:forwarding_url] = request.url if request.get?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/diaries/_diary.html.erb
<li id="diary-<%= diary.id %>">
  <%= link_to gravatar_for(diary.user, size: 50), diary.user %>
  <span class="user"><%= link_to diary.user.name, diary.user %></span>
  <h3 class="title"><%= diary.title %></h3>
  <span class="content">
    <%= truncate(diary.content) %><br>
    <%= link_to "本文を読む", diary_path(diary) %>
  </span>
  <span class="timestamp">
    ( Written on <%= diary.created_at.strftime("%Y-%m-%d %H:%M:%S") %> )
    <% if current_user == diary.user %>
      <%= link_to "削除", diary, method: :delete,
                                       data: { confirm: "削除しますか？" } %>
    <% end %>
  </span>
</li>

app/views/diaries/show.html.erb
<div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
        <%= render "words/word" %>
      </section>
    </aside>

    <div class="col-md-8">
      <%= link_to gravatar_for(@diary.user, size: 50), @diary.user %>
      <span class="user"><%= link_to @diary.user.name, @diary.user %></span><br>
      <h3 class="title"><%= @diary.title %></h3><br>
      <span class="content"><%= @diary.content %><br></span><br>
      <span class="timestamp">
        ( Written on <%= @diary.created_at.strftime("%Y-%m-%d %H:%M:%S") %> )
        <% if current_user == @diary.user %>
          <%= link_to "delete", @diary, method: :delete,
                                           data: { confirm: "You sure?" } %>
        <% end %>
      </span>
    </div>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Diary", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "ホーム", root_path %></li>
        <% if logged_in? %>
        <li><%= link_to "日記を書く", new_diary_user_path(current_user) %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              アカウント <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "プロフィール", current_user %></li>
              <li><%= link_to "設定", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "ログアウト", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "ログイン", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Diary</title>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/relationships/create.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/unfollow')) %>");

app/views/relationships/destroy.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/follow')) %>");

app/views/shared/_diary_form.html.erb
<%= form_for(current_user.diaries.build) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.label :title, "タイトル : " %>
    <%= f.text_area :title, placeholder:"タイトル" %>
    <span class="content">
    <%= f.label :content, "本文 : " %>  
    <%= f.text_area :content, placeholder: "本文", rows:"10" %>
    </span>
  </div>
  <%= f.submit "投稿", class: "btn btn-primary" %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      エラー <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="diaries">
    <%= render @feed_items %>
  </ol>
<% end %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
    <h1><%= current_user.name %></h1>
    <span><%= link_to "プロフィールを見る", current_user %></span>
    <span><%= pluralize(current_user.diaries.count, "diary") %></span>
    <% if current_user.location.presence %><span class="location">地域 : <%= current_user.location %></span><br><% end %>
    <% if current_user.hobby.presence %><span class="hobby">趣味 : <%= current_user.hobby %></span><br><% end %>
    <% if current_user.thema.presence %><span class="thema">テーマ : <%= current_user.thema %></span><br><% end %>
    <span class="follow-followed">
      <%= link_to "フォロー",followings_user_path(current_user) %>(<%= current_user.following_users.count %>) /
      <%= link_to "フォロワー", followers_user_path(current_user) %>(<%= current_user.follower_users.count %>)
    </span>
    <span class="diary-post">
      <br>
      <%= link_to "日記を書く", new_diary_user_path(current_user) %>
    </span>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
        <%= render "words/word" %>
      </section>
    </aside>
    <div class="col-md-8">
      <h3>Diary</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
  <div class="col-md-4">
    
  </div>
<% else %>
  <div class="center jumbotron">
    <h1>Welcome to the Diary</h1>

    <%= link_to "アカウント登録", signup_path, class: "btn btn-lg btn-primary" %>　　
    <%= link_to "ログイン", login_path, class: "btn btn-lg btn-info" %>

  </div>
<% end %>

app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "フォロー", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% if current_user != @user %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "フォロー解除", class: "btn" %>
<% end %>

app/views/users/edit.html.erb
<h1>登録情報変更</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %> 

      <%= f.label :name,"名前" %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
      
      <%= f.label :location, "地域" %>
      <%= f.text_field :location, class: 'form-control' %>
      
      <%= f.label :hobby, "趣味" %>
      <%= f.text_field :hobby, class: 'form-control' %>
      
      <%= f.label :thema, "テーマ" %>
      <%= f.text_field :thema, class: 'form-control' %>

      <%= f.label :password, "パスワード (変更)" %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "パスワード確認" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "更新", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/followers.html.erb
<%# @f_users %>
<h3>フォロワーリスト</h3>
<% @f_users.each do |user| %>
    <%= gravatar_for(user, size:35) %><br>
    <%= link_to user.name, user %><br>
<% end %>

app/views/users/followings.html.erb
<%# @f_users %>
<h3>フォローリスト</h3>
<% @f_users.each do |user| %>
    <%= gravatar_for(user, size:35) %><br>
    <%= link_to user.name, user %><br>
<% end %>

app/views/users/new.html.erb
<h1>アカウント登録</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %> 

      <%= f.label :name, "名前" %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password, "パスワード" %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "パスワード確認" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "アカウントを作る", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/new_diary.html.erb
<div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      　<%= render "words/word" %>
      </section>
    </aside>
        <div class="col-md-8">
            <h3>投稿フォーム</h3>
            <%= render 'shared/diary_form' %>
        </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <div class="info_top">
        <h1>
          <span class="icon"><%= gravatar_for @user %></span><br><br><br>
          <span class="name">名前 : <%= @user.name %></span>
        </h1>
      </div>
      <hr>
      <div class="info_body">
        <% if @user.location.presence %><span class="location">地域 : <%= @user.location %></span><br><% end %>
        <% if @user.hobby.presence %><span class="hobby">趣味 : <%= @user.hobby %></span><br><% end %>
        <% if @user.thema.presence %><span class="thema">テーマ : <%= @user.thema %></span><br><% end %>
        <span class="follow-followed">
          <%= link_to "フォロー",followings_user_path(@user) %> /
          <%= link_to "フォロワー", followers_user_path(@user) %>
        </span>
      </div>
    </section>
        <%= render 'follow_form' if logged_in? %>
        <%= render 'words/word' if current_user==@user %>
  </aside>
  <div class="col-md-8">
      <% if @user.diaries.any? %>
        <h3>Diaries (<%= @user.diaries.count %>)</h3>
        <% @user.diaries.each do |diary| %>
        <ol id="diary-<%= diary.id %>">
            <h3 class="title"><%= diary.title %></h3>
            <span class="content"><%= diary.content %></span><br>
                <%= link_to "本文を読む", diary_path(diary) %><br>
            <span class="timestamp">
              ( Written on <%= diary.created_at.strftime("%Y-%m-%d %H:%M:%S") %> )
              <% if current_user == diary.user %>
                <%= link_to "削除", diary, method: :delete,
                                                 data: { confirm: "削除しますか？" } %>
              <% end %>
            </span>
        </ol>
        <hr>
        <% end %>
      <% end %>
  </div>
</div>

app/views/words/_word.html.erb
<h4>用語検索</h4>
<%= form_for current_user.words.build do |f| %>
      <%= f.text_field :keyword, placeholder:"英語/日本語" %>
      <%= f.submit "検索", class: "btn btn-primary" %>
<% end %>
<h4>検索履歴</h4>
<div class="history">
        <% current_user.words.limit(20).order(created_at: :desc).each do |word| %>
            <%= link_to word.keyword, URI.escape("http://ejje.weblio.jp/content/#{word.keyword}"), target:"_blank" %><br>
        <% end %>
</div>